# Generated by Django 4.1.2 on 2022-10-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quartet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartets', to='main_app.folio')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('annote', models.TextField(blank=True, max_length=150)),
                ('quartet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main_app.quartet')),
            ],
        ),
    ]
