# Generated by Django 4.1.2 on 2022-10-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folio',
            options={},
        ),
        migrations.RemoveField(
            model_name='folio',
            name='created_at',
        ),
    ]
