# Generated by Django 4.1.2 on 2022-10-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_entry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='annote',
            new_name='annotate',
        ),
    ]
