# Generated by Django 4.1.2 on 2022-10-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_annote_entry_annotate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='url',
            new_name='embed',
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
